CompanyWeb/Models/ErrorViewModel.cs
namespace CompanyWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CompanyWeb/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.IdentityModel.Tokens;
using Company.Application.DTOs;
using Company.Infrastructure.Repositories;
using Company.Application.Interface;

namespace CompanyWeb.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
     
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto loginRequest)
        {
            var user = await _userService.AuthenticateAsync(
                loginRequest.UserName, loginRequest.Password);

            if (user != null)
            {
                //Generate JWT
           //     var token = await tokenHandler.CreateTokenAsync(user);
                // return Ok(token);
                return View("Index");
            }

            return BadRequest("username and password is incorect");
        }

    }
}

CompanyWeb/Controllers/HomeController.cs
using System.Diagnostics;
using CompanyWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace CompanyWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CompanyWeb/Controllers/VillaController.cs
using Company.Application.Services;
using Company.Application.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Company.Application.Interface;

namespace CompanyWeb.Controllers
{ 
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
       // private readonly IGenericService<VillaDto, CreateUpdateVillaDto> _villaService;

        public VillaController(IVillaService villaService)
        {
            _villaService = villaService;
        }

        public async Task<IActionResult> Index()
        {
            var villas = await _villaService.GetVillasAsync();
            return View(villas);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Prevent CSRF attacks
        public async Task<IActionResult> Create(CreateUpdateVillaDto dto)
        {
            await _villaService.AddVillasAsync(dto);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int villaId)
        {
            var villa = await _villaService.GetVillasByIdAsync(villaId);
            if (villa == null)
                return NotFound();

            var villaDto = new VillaDto
            {
                Name = villa.Name,
                Description = villa.Description,
                Id = villa.Id,
            };

            return View(villaDto);
        }

        [HttpPost]
        public async Task<IActionResult> Update(VillaDto dto)
        {
            int id = dto.Id;
            var result = await _villaService.UpdateVillasAsync(dto);
            if (result)
                return RedirectToAction("Index");

            return NotFound();
        }


        public async Task<IActionResult> Delete(int villaId)
        {
            var result = await _villaService.DeleteVillasAsync(villaId);
            if (!result)
                return NotFound();

            return RedirectToAction("Index");
        }
    }
}

CompanyWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

CompanyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CompanyWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @*  <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CompanyWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> *@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Villa" asp-action="Index">Villa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CompanyWeb 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CompanyWeb/Views/Villa/Create.cshtml
@model Company.Application.DTOs.CreateUpdateVillaDto
<h2>Create Villa</h2>
<div>
    <form asp-action="Create" method="post">
        <div>
            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" />
                <span asp-validation-for="Name" class="alert-danger"></span>
            </div>
            <div>
                <label asp-for="Description"></label>
                <input asp-for="Description" />
            
            </div>
      @*       <div>
                <label asp-for="CreateDate"></label>
                <input asp-for="CreateDate" />
               
            </div>
            <div>
                <label asp-for="UpdateDate"></label>
                <input asp-for="UpdateDate" />
            </div> *@
        </div>
        <div>
            <button type="submit">Create</button>
            <a asp-controller="Villa" asp-action="Index"> Cancel</a>
        </div>
    </form>
</div>

CompanyWeb/Views/Villa/Index.cshtml
@model IEnumerable<Company.Application.DTOs.VillaDto>
<a asp-controller="Villa" asp-action="Create">Create New Villa</a>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
           @*  <th>Create Date</th>
            <th>Update Date</th> *@
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td >@obj.Name</td>
                <td>@obj.Description</td>
            @*     <td>@obj.CreateDate</td>
                <td>@obj.UpdateDate</td> *@
                <td>
                    <a asp-controller="Villa" asp-action="Update" asp-route-villaId="@obj.Id">EDIT</a>
                </td>
                <td>
                    <a asp-controller="Villa" asp-action="Delete" asp-route-villaId="@obj.Id">Delete</a>
                </td>
            </tr>
        }
        
    </tbody>
</table>

CompanyWeb/Views/Villa/Update.cshtml
@model Company.Application.DTOs.VillaDto
<h2>Edit Villa</h2>
<div>
    <form method="post" asp-action="Update">
        <input asp-for="Id" type="hidden"/>
        <div>
            <label asp-for="Name" ></label>
            <input asp-for="Name" />
        </div>
        <div>
            <label asp-for="Description"></label>
            <input asp-for="Description"/>
        </div>
      @*   <div>
            <label asp-for="CreateDate"></label>
            <input asp-for="CreateDate"/>
        </div>
        <div>
            <label asp-for="UpdateDate"></label>
            <input asp-for="UpdateDate" />
        </div> *@
        <button type="submit">Update</button>
    </form>
</div>